//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_ClassCleaner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\t\t    GNU GENERAL PUBLIC LICENSE\r\n\t\t       Version 2, June 1991\r\n\r\n Copyright (C)" +
            " 1989, 1991 Free Software Foundation, Inc.,\r\n 51 Franklin Street, Fifth Floor, B" +
            "oston, MA 02110-1301 USA\r\n Everyone is permitted to copy and distribute verbatim" +
            " copies\r\n of this license document, but changing it is not allowed.\r\n\r\n\t\t\t    Pr" +
            "eamble\r\n\r\n  The licenses for most software are designed to take away your\r\nfreed" +
            "om to share and change it.  By contrast, the GNU General Public\r\nLicense is inte" +
            "nded to guarantee your freedom to share and change free\r\nsoftware--to make sure " +
            "the software is free for all its users.  This\r\nGeneral Public License applies to" +
            " most of the Free Software\r\nFoundation\'s software and to any other program whose" +
            " authors commit to\r\nusing it.  (Some other Free Software Foundation software is " +
            "covered by\r\nthe GNU Lesser General Public License instead.)  You can apply it to" +
            "\r\nyour programs, too.\r\n\r\n  When we speak of free software, we are referring to f" +
            "reedom, not\r\nprice.  Our General Public Licenses are designed to make sure that " +
            "you\r\nhave the freedom to distribute copies of free software (and charge for\r\nthi" +
            "s service if you wish), that you receive source code or can get it\r\nif you want " +
            "it, that you can change the software or use pieces of it\r\nin new free programs; " +
            "and that you know you can do these things.\r\n\r\n  To protect your rights, we need " +
            "to make restrictions that forbid\r\nanyone to deny you these rights or to ask you " +
            "to surrender the rights.\r\nThese restrictions translate to certain responsibiliti" +
            "es for you if you\r\ndistribute copies of the software, or if you modify it.\r\n\r\n  " +
            "For example, if you distribute copies of such a program, whether\r\ngratis or for " +
            "a fee, you must give the recipients all the rights that\r\nyou have.  You must mak" +
            "e sure that they, too, receive or can get the\r\nsource code.  And you must show t" +
            "hem these terms so they know their\r\nrights.\r\n\r\n  We protect your rights with two" +
            " steps: (1) copyright the software, and\r\n(2) offer you this license which gives " +
            "you legal permission to copy,\r\ndistribute and/or modify the software.\r\n\r\n  Also," +
            " for each author\'s protection and ours, we want to make certain\r\nthat everyone u" +
            "nderstands that there is no warranty for this free\r\nsoftware.  If the software i" +
            "s modified by someone else and passed on, we\r\nwant its recipients to know that w" +
            "hat they have is not the original, so\r\nthat any problems introduced by others wi" +
            "ll not reflect on the original\r\nauthors\' reputations.\r\n\r\n  Finally, any free pro" +
            "gram is threatened constantly by software\r\npatents.  We wish to avoid the danger" +
            " that redistributors of a free\r\nprogram will individually obtain patent licenses" +
            ", in effect making the\r\nprogram proprietary.  To prevent this, we have made it c" +
            "lear that any\r\npatent must be licensed for everyone\'s free use or not licensed a" +
            "t all.\r\n\r\n  The precise terms and conditions for copying, distribution and\r\nmodi" +
            "fication follow.\r\n\r\n\t\t    GNU GENERAL PUBLIC LICENSE\r\n   TERMS AND CONDITIONS FO" +
            "R COPYING, DISTRIBUTION AND MODIFICATION\r\n\r\n  0. This License applies to any pro" +
            "gram or other work which contains\r\na notice placed by the copyright holder sayin" +
            "g it may be distributed\r\nunder the terms of this General Public License.  The \"P" +
            "rogram\", below,\r\nrefers to any such program or work, and a \"work based on the Pr" +
            "ogram\"\r\nmeans either the Program or any derivative work under copyright law:\r\nth" +
            "at is to say, a work containing the Program or a portion of it,\r\neither verbatim" +
            " or with modifications and/or translated into another\r\nlanguage.  (Hereinafter, " +
            "translation is included without limitation in\r\nthe term \"modification\".)  Each l" +
            "icensee is addressed as \"you\".\r\n\r\nActivities other than copying, distribution an" +
            "d modification are not\r\ncovered by this License; they are outside its scope.  Th" +
            "e act of\r\nrunning the Program is not restricted, and the output from the Program" +
            "\r\nis covered only if its contents constitute a work based on the\r\nProgram (indep" +
            "endent of having been made by running the Program).\r\nWhether that is true depend" +
            "s on what the Program does.\r\n\r\n  1. You may copy and distribute verbatim copies " +
            "of the Program\'s\r\nsource code as you receive it, in any medium, provided that yo" +
            "u\r\nconspicuously and appropriately publish on each copy an appropriate\r\ncopyrigh" +
            "t notice and disclaimer of warranty; keep intact all the\r\nnotices that refer to " +
            "this License and to the absence of any warranty;\r\nand give any other recipients " +
            "of the Program a copy of this License\r\nalong with the Program.\r\n\r\nYou may charge" +
            " a fee for the physical act of transferring a copy, and\r\nyou may at your option " +
            "offer warranty protection in exchange for a fee.\r\n\r\n  2. You may modify your cop" +
            "y or copies of the Program or any portion\r\nof it, thus forming a work based on t" +
            "he Program, and copy and\r\ndistribute such modifications or work under the terms " +
            "of Section 1\r\nabove, provided that you also meet all of these conditions:\r\n\r\n   " +
            " a) You must cause the modified files to carry prominent notices\r\n    stating th" +
            "at you changed the files and the date of any change.\r\n\r\n    b) You must cause an" +
            "y work that you distribute or publish, that in\r\n    whole or in part contains or" +
            " is derived from the Program or any\r\n    part thereof, to be licensed as a whole" +
            " at no charge to all third\r\n    parties under the terms of this License.\r\n\r\n    " +
            "c) If the modified program normally reads commands interactively\r\n    when run, " +
            "you must cause it, when started running for such\r\n    interactive use in the mos" +
            "t ordinary way, to print or display an\r\n    announcement including an appropriat" +
            "e copyright notice and a\r\n    notice that there is no warranty (or else, saying " +
            "that you provide\r\n    a warranty) and that users may redistribute the program un" +
            "der\r\n    these conditions, and telling the user how to view a copy of this\r\n    " +
            "License.  (Exception: if the Program itself is interactive but\r\n    does not nor" +
            "mally print such an announcement, your work based on\r\n    the Program is not req" +
            "uired to print an announcement.)\r\n\r\nThese requirements apply to the modified wor" +
            "k as a whole.  If\r\nidentifiable sections of that work are not derived from the P" +
            "rogram,\r\nand can be reasonably considered independent and separate works in\r\nthe" +
            "mselves, then this License, and its terms, do not apply to those\r\nsections when " +
            "you distribute them as separate works.  But when you\r\ndistribute the same sectio" +
            "ns as part of a whole which is a work based\r\non the Program, the distribution of" +
            " the whole must be on the terms of\r\nthis License, whose permissions for other li" +
            "censees extend to the\r\nentire whole, and thus to each and every part regardless " +
            "of who wrote it.\r\n\r\nThus, it is not the intent of this section to claim rights o" +
            "r contest\r\nyour rights to work written entirely by you; rather, the intent is to" +
            "\r\nexercise the right to control the distribution of derivative or\r\ncollective wo" +
            "rks based on the Program.\r\n\r\nIn addition, mere aggregation of another work not b" +
            "ased on the Program\r\nwith the Program (or with a work based on the Program) on a" +
            " volume of\r\na storage or distribution medium does not bring the other work under" +
            "\r\nthe scope of this License.\r\n\r\n  3. You may copy and distribute the Program (or" +
            " a work based on it,\r\nunder Section 2) in object code or executable form under t" +
            "he terms of\r\nSections 1 and 2 above provided that you also do one of the followi" +
            "ng:\r\n\r\n    a) Accompany it with the complete corresponding machine-readable\r\n   " +
            " source code, which must be distributed under the terms of Sections\r\n    1 and 2" +
            " above on a medium customarily used for software interchange; or,\r\n\r\n    b) Acco" +
            "mpany it with a written offer, valid for at least three\r\n    years, to give any " +
            "third party, for a charge no more than your\r\n    cost of physically performing s" +
            "ource distribution, a complete\r\n    machine-readable copy of the corresponding s" +
            "ource code, to be\r\n    distributed under the terms of Sections 1 and 2 above on " +
            "a medium\r\n    customarily used for software interchange; or,\r\n\r\n    c) Accompany" +
            " it with the information you received as to the offer\r\n    to distribute corresp" +
            "onding source code.  (This alternative is\r\n    allowed only for noncommercial di" +
            "stribution and only if you\r\n    received the program in object code or executabl" +
            "e form with such\r\n    an offer, in accord with Subsection b above.)\r\n\r\nThe sourc" +
            "e code for a work means the preferred form of the work for\r\nmaking modifications" +
            " to it.  For an executable work, complete source\r\ncode means all the source code" +
            " for all modules it contains, plus any\r\nassociated interface definition files, p" +
            "lus the scripts used to\r\ncontrol compilation and installation of the executable." +
            "  However, as a\r\nspecial exception, the source code distributed need not include" +
            "\r\nanything that is normally distributed (in either source or binary\r\nform) with " +
            "the major components (compiler, kernel, and so on) of the\r\noperating system on w" +
            "hich the executable runs, unless that component\r\nitself accompanies the executab" +
            "le.\r\n\r\nIf distribution of executable or object code is made by offering\r\naccess " +
            "to copy from a designated place, then offering equivalent\r\naccess to copy the so" +
            "urce code from the same place counts as\r\ndistribution of the source code, even t" +
            "hough third parties are not\r\ncompelled to copy the source along with the object " +
            "code.\r\n\r\n  4. You may not copy, modify, sublicense, or distribute the Program\r\ne" +
            "xcept as expressly provided under this License.  Any attempt\r\notherwise to copy," +
            " modify, sublicense or distribute the Program is\r\nvoid, and will automatically t" +
            "erminate your rights under this License.\r\nHowever, parties who have received cop" +
            "ies, or rights, from you under\r\nthis License will not have their licenses termin" +
            "ated so long as such\r\nparties remain in full compliance.\r\n\r\n  5. You are not req" +
            "uired to accept this License, since you have not\r\nsigned it.  However, nothing e" +
            "lse grants you permission to modify or\r\ndistribute the Program or its derivative" +
            " works.  These actions are\r\nprohibited by law if you do not accept this License." +
            "  Therefore, by\r\nmodifying or distributing the Program (or any work based on the" +
            "\r\nProgram), you indicate your acceptance of this License to do so, and\r\nall its " +
            "terms and conditions for copying, distributing or modifying\r\nthe Program or work" +
            "s based on it.\r\n\r\n  6. Each time you redistribute the Program (or any work based" +
            " on the\r\nProgram), the recipient automatically receives a license from the\r\norig" +
            "inal licensor to copy, distribute or modify the Program subject to\r\nthese terms " +
            "and conditions.  You may not impose any further\r\nrestrictions on the recipients\'" +
            " exercise of the rights granted herein.\r\nYou are not responsible for enforcing c" +
            "ompliance by third parties to\r\nthis License.\r\n\r\n  7. If, as a consequence of a c" +
            "ourt judgment or allegation of patent\r\ninfringement or for any other reason (not" +
            " limited to patent issues),\r\nconditions are imposed on you (whether by court ord" +
            "er, agreement or\r\notherwise) that contradict the conditions of this License, the" +
            "y do not\r\nexcuse you from the conditions of this License.  If you cannot\r\ndistri" +
            "bute so as to satisfy simultaneously your obligations under this\r\nLicense and an" +
            "y other pertinent obligations, then as a consequence you\r\nmay not distribute the" +
            " Program at all.  For example, if a patent\r\nlicense would not permit royalty-fre" +
            "e redistribution of the Program by\r\nall those who receive copies directly or ind" +
            "irectly through you, then\r\nthe only way you could satisfy both it and this Licen" +
            "se would be to\r\nrefrain entirely from distribution of the Program.\r\n\r\nIf any por" +
            "tion of this section is held invalid or unenforceable under\r\nany particular circ" +
            "umstance, the balance of the section is intended to\r\napply and the section as a " +
            "whole is intended to apply in other\r\ncircumstances.\r\n\r\nIt is not the purpose of " +
            "this section to induce you to infringe any\r\npatents or other property right clai" +
            "ms or to contest validity of any\r\nsuch claims; this section has the sole purpose" +
            " of protecting the\r\nintegrity of the free software distribution system, which is" +
            "\r\nimplemented by public license practices.  Many people have made\r\ngenerous cont" +
            "ributions to the wide range of software distributed\r\nthrough that system in reli" +
            "ance on consistent application of that\r\nsystem; it is up to the author/donor to " +
            "decide if he or she is willing\r\nto distribute software through any other system " +
            "and a licensee cannot\r\nimpose that choice.\r\n\r\nThis section is intended to make t" +
            "horoughly clear what is believed to\r\nbe a consequence of the rest of this Licens" +
            "e.\r\n\r\n  8. If the distribution and/or use of the Program is restricted in\r\ncerta" +
            "in countries either by patents or by copyrighted interfaces, the\r\noriginal copyr" +
            "ight holder who places the Program under this License\r\nmay add an explicit geogr" +
            "aphical distribution limitation excluding\r\nthose countries, so that distribution" +
            " is permitted only in or among\r\ncountries not thus excluded.  In such case, this" +
            " License incorporates\r\nthe limitation as if written in the body of this License." +
            "\r\n\r\n  9. The Free Software Foundation may publish revised and/or new versions\r\no" +
            "f the General Public License from time to time.  Such new versions will\r\nbe simi" +
            "lar in spirit to the present version, but may differ in detail to\r\naddress new p" +
            "roblems or concerns.\r\n\r\nEach version is given a distinguishing version number.  " +
            "If the Program\r\nspecifies a version number of this License which applies to it a" +
            "nd \"any\r\nlater version\", you have the option of following the terms and conditio" +
            "ns\r\neither of that version or of any later version published by the Free\r\nSoftwa" +
            "re Foundation.  If the Program does not specify a version number of\r\nthis Licens" +
            "e, you may choose any version ever published by the Free Software\r\nFoundation.\r\n" +
            "\r\n  10. If you wish to incorporate parts of the Program into other free\r\nprogram" +
            "s whose distribution conditions are different, write to the author\r\nto ask for p" +
            "ermission.  For software which is copyrighted by the Free\r\nSoftware Foundation, " +
            "write to the Free Software Foundation; we sometimes\r\nmake exceptions for this.  " +
            "Our decision will be guided by the two goals\r\nof preserving the free status of a" +
            "ll derivatives of our free software and\r\nof promoting the sharing and reuse of s" +
            "oftware generally.\r\n\r\n\t\t\t    NO WARRANTY\r\n\r\n  11. BECAUSE THE PROGRAM IS LICENSE" +
            "D FREE OF CHARGE, THERE IS NO WARRANTY\r\nFOR THE PROGRAM, TO THE EXTENT PERMITTED" +
            " BY APPLICABLE LAW.  EXCEPT WHEN\r\nOTHERWISE STATED IN WRITING THE COPYRIGHT HOLD" +
            "ERS AND/OR OTHER PARTIES\r\nPROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY OF ANY KI" +
            "ND, EITHER EXPRESSED\r\nOR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WAR" +
            "RANTIES OF\r\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RI" +
            "SK AS\r\nTO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE\r\nP" +
            "ROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,\r\nREPAIR " +
            "OR CORRECTION.\r\n\r\n  12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED " +
            "TO IN WRITING\r\nWILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/" +
            "OR\r\nREDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES,\r\n" +
            "INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING\r\nOUT" +
            " OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED\r\nTO LOSS " +
            "OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY\r\nYOU OR THIRD P" +
            "ARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER\r\nPROGRAMS), EVEN IF" +
            " SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE\r\nPOSSIBILITY OF SUCH DAMAGES" +
            ".\r\n\r\n\t\t     END OF TERMS AND CONDITIONS\r\n\r\n\t    How to Apply These Terms to Your" +
            " New Programs\r\n\r\n  If you develop a new program, and you want it to be of the gr" +
            "eatest\r\npossible use to the public, the best way to achieve this is to make it\r\n" +
            "free software which everyone can redistribute and change under these terms.\r\n\r\n " +
            " To do so, attach the following notices to the program.  It is safest\r\nto attach" +
            " them to the start of each source file to most effectively\r\nconvey the exclusion" +
            " of warranty; and each file should have at least\r\nthe \"copyright\" line and a poi" +
            "nter to where the full notice is found.\r\n\r\n    <one line to give the program\'s n" +
            "ame and a brief idea of what it does.>\r\n    Copyright (C) <year>  <name of autho" +
            "r>\r\n\r\n    This program is free software; you can redistribute it and/or modify\r\n" +
            "    it under the terms of the GNU General Public License as published by\r\n    th" +
            "e Free Software Foundation; either version 2 of the License, or\r\n    (at your op" +
            "tion) any later version.\r\n\r\n    This program is distributed in the hope that it " +
            "will be useful,\r\n    but WITHOUT ANY WARRANTY; without even the implied warranty" +
            " of\r\n    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\r\n    GNU " +
            "General Public License for more details.\r\n\r\n    You should have received a copy " +
            "of the GNU General Public License along\r\n    with this program; if not, write to" +
            " the Free Software Foundation, Inc.,\r\n    51 Franklin Street, Fifth Floor, Bosto" +
            "n, MA 02110-1301 USA.\r\n\r\nAlso add information on how to contact you by electroni" +
            "c and paper mail.\r\n\r\nIf the program is interactive, make it output a short notic" +
            "e like this\r\nwhen it starts in an interactive mode:\r\n\r\n    Gnomovision version 6" +
            "9, Copyright (C) year name of author\r\n    Gnomovision comes with ABSOLUTELY NO W" +
            "ARRANTY; for details type `show w\'.\r\n    This is free software, and you are welc" +
            "ome to redistribute it\r\n    under certain conditions; type `show c\' for details." +
            "\r\n\r\nThe hypothetical commands `show w\' and `show c\' should show the appropriate\r" +
            "\nparts of the General Public License.  Of course, the commands you use may\r\nbe c" +
            "alled something other than `show w\' and `show c\'; they could even be\r\nmouse-clic" +
            "ks or menu items--whatever suits your program.\r\n\r\nYou should also get your emplo" +
            "yer (if you work as a programmer) or your\r\nschool, if any, to sign a \"copyright " +
            "disclaimer\" for the program, if\r\nnecessary.  Here is a sample; alter the names:\r" +
            "\n\r\n  Yoyodyne, Inc., hereby disclaims all copyright interest in the program\r\n  `" +
            "Gnomovision\' (which makes passes at compilers) written by James Hacker.\r\n\r\n  <si" +
            "gnature of Ty Coon>, 1 April 1989\r\n  Ty Coon, President of Vice\r\n\r\nThis General " +
            "Public License does not permit incorporating your program into\r\nproprietary prog" +
            "rams.  If your program is a subroutine library, you may\r\nconsider it more useful" +
            " to permit linking proprietary applications with the\r\nlibrary.  If this is what " +
            "you want to do, use the GNU Lesser General\r\nPublic License instead of this Licen" +
            "se.")]
        public string LicenseAgreement {
            get {
                return ((string)(this["LicenseAgreement"]));
            }
        }
    }
}
